name: bmspeech
channels:
- defaults
dependencies:
- gensim=1.0.1
- ipython=6.0.0=py35_0
- jupyter=1.0.0=py35_3
- nltk=3.2.2=py35_0
- numpy=1.12.1=py35_0
- python=3.5.3=1
- pip:
  - spacy==1.8.2
  - wordcloud==1.3.1
